// Generated from shared/lite-topic-contract.json (SHA-256 bc74706a452ca33d2076283a07c1cd4280d00a3b623b906c2fc6e0f6a36f4f00). Do not edit.
package com.eltnegcellist.emma.ai

internal object LiteTopicContractFixtures {
    data class Case(val id: String, val text: String, val scene: String, val meaningful: Boolean)
    data class Step(val text: String? = null, val scene: String? = null,
                    val meaningful: Boolean = true, val reset: Boolean = false)
    data class Sequence(val id: String, val steps: List<Step>)
    const val CONTEXT_FOLLOWUP_TURNS = 6
    val cases = listOf(
        Case("case-001", "てがみだよ", "generic", true),
        Case("case-002", "ほんとだね", "generic", true),
        Case("case-003", "ほんとうだね", "generic", true),
        Case("case-004", "こんにちは そろそろ寝ましょうね", "sleep", true),
        Case("case-005", "そろそろねましょうね", "sleep", true),
        Case("case-006", "もう寝ちゃったね", "sleep", true),
        Case("case-007", "ねむくなってきましたね", "sleep", true),
        Case("case-008", "そろそろ寝ませんか", "sleep", true),
        Case("case-009", "お昼寝の時間ですよ", "sleep", true),
        Case("case-010", "こんにちは、おふろに入りましょう", "bath", true),
        Case("case-011", "からだを洗いましょうね", "bath", true),
        Case("case-012", "おふらに入ろうね", "bath", true),
        Case("case-013", "ミルクを飲みましょうね", "milk", true),
        Case("case-014", "みるこを飲もうね", "milk", true),
        Case("case-015", "みりく飲もうか", "milk", true),
        Case("case-016", "ぼにゅうにしようね", "milk", true),
        Case("case-017", "ほにゅうびんだよ", "milk", true),
        Case("case-018", "そろそろ起きましょうね", "wake", true),
        Case("case-019", "おきましょうね", "wake", true),
        Case("case-020", "目を覚ましたね", "wake", true),
        Case("case-021", "おむつを取り替えましょう", "diaper", true),
        Case("case-022", "おむちをかえようね", "diaper", true),
        Case("case-023", "おしっこが出ましたね", "diaper", true),
        Case("case-024", "きがえましょうね", "clothes", true),
        Case("case-025", "洋服を着ましょうね", "clothes", true),
        Case("case-026", "ぱじゃまに着替えよう", "clothes", true),
        Case("case-027", "だっこしましょうね", "hug", true),
        Case("case-028", "だつこしようか", "hug", true),
        Case("case-029", "ぎゅっと抱きしめよう", "hug", true),
        Case("case-030", "おててをにぎってるね", "hands", true),
        Case("case-031", "てをにぎりましょうね", "hands", true),
        Case("case-032", "ゆびをつかんだね", "hands", true),
        Case("case-033", "あんよがばたばたしてるね", "feet", true),
        Case("case-034", "あしを動かしてるね", "feet", true),
        Case("case-035", "足を蹴っているね", "feet", true),
        Case("case-036", "かわいいえがおですね", "smile", true),
        Case("case-037", "にこにこしていますね", "smile", true),
        Case("case-038", "わらってるね", "smile", true),
        Case("case-039", "ないちゃったね", "cry", true),
        Case("case-040", "ぐずぐずしてるね", "cry", true),
        Case("case-041", "泣いていますね", "cry", true),
        Case("case-042", "ないてるね", "cry", true),
        Case("case-043", "こえを出しているね", "voice", true),
        Case("case-044", "おしゃべりしていますね", "voice", true),
        Case("case-045", "なんごが出たね", "voice", true),
        Case("case-046", "げっぷが出ましたね", "tummy", true),
        Case("case-047", "げつぷが出たね", "tummy", true),
        Case("case-048", "おなかいっぱいですね", "tummy", true),
        Case("case-049", "いっしょに遊びましょうね", "play", true),
        Case("case-050", "あそびましょうね", "play", true),
        Case("case-051", "おもちょで遊ぼうね", "play", true),
        Case("case-052", "さんぽに行きましょうね", "outside", true),
        Case("case-053", "べびーかーでお出かけしよう", "outside", true),
        Case("case-054", "こうえんに行こうね", "outside", true),
        Case("case-055", "あめが降っていますね", "rain", true),
        Case("case-056", "あまおとが聞こえるね", "rain", true),
        Case("case-057", "はれてきましたね", "sun", true),
        Case("case-058", "たいようが出ているね", "sun", true),
        Case("case-059", "ぽかぽかしていますね", "sun", true),
        Case("case-060", "ごはんを食べましょうね", "food", true),
        Case("case-061", "たべましょうね", "food", true),
        Case("case-062", "りにゅうしょくだよ", "food", true),
        Case("case-063", "おなかがすいたね", "food", true),
        Case("case-064", "えほんを読みましょうね", "book", true),
        Case("case-065", "えほうを読もうね", "book", true),
        Case("case-066", "ほんをよみましょうね", "book", true),
        Case("case-067", "うたを歌いましょうね", "music", true),
        Case("case-068", "おんがき聞こうね", "music", true),
        Case("case-069", "踊りましょうね", "music", true),
        Case("case-070", "こんにちは、今日もよろしくね", "generic", true),
        Case("case-071", "今日は会社で会議だったよ", "generic", true),
        Case("case-072", "今日はゆっくりしようね", "generic", true),
        Case("case-073", "かわいいね", "generic", true),
        Case("case-074", "いい感じですね", "generic", true),
        Case("case-075", "そろそろ帰りましょうね", "generic", true),
        Case("case-076", "お手紙を書きましょう", "generic", true),
        Case("case-077", "手続きをしましょう", "generic", true),
        Case("case-078", "手伝いましょうね", "generic", true),
        Case("case-079", "足りないですね", "generic", true),
        Case("case-080", "明日の予定を決めましょう", "generic", true),
        Case("case-081", "風呂敷を包みましょう", "generic", true),
        Case("case-082", "ふろしきを包もうね", "generic", true),
        Case("case-083", "歌舞伎を見よう", "generic", true),
        Case("case-084", "かぶきを見よう", "generic", true),
        Case("case-085", "声優さんの話だよ", "generic", true),
        Case("case-086", "せいゆうさんの話だよ", "generic", true),
        Case("case-087", "寝返りしましたね", "generic", true),
        Case("case-088", "ねがえりしたね", "generic", true),
        Case("case-089", "本当にそうですね", "generic", true),
        Case("case-090", "飴を買いましょう", "generic", true),
        Case("case-091", "紙を重ねるよ", "generic", true),
        Case("case-092", "みるこさんに会ったよ", "generic", true),
        Case("case-093", "紙を重ねましょう", "generic", true),
        Case("case-094", "かさねておきましょう", "generic", true),
        Case("case-095", "真似ましょう", "generic", true),
        Case("case-096", "友達をたずねましょう", "generic", true),
        Case("case-097", "飲もうか", "drink", true),
        Case("case-098", "飲むかい", "drink", true),
        Case("case-099", "飲む？", "drink", true),
        Case("case-100", "飲みたい？", "drink", true),
        Case("case-101", "飲んだね", "drink", true),
        Case("case-102", "飲んでみよう", "drink", true),
        Case("case-103", "飲みましょうね", "drink", true),
        Case("case-104", "そろそろ飲む会", "drink", true),
        Case("case-105", "そろそろ飲むかい？", "drink", true),
        Case("case-106", "のむ？", "drink", true),
        Case("case-107", "のみたい？", "drink", true),
        Case("case-108", "のもうか", "drink", true),
        Case("case-109", "そろそろのむかい", "drink", true),
        Case("case-110", "もうのんだね", "drink", true),
        Case("case-111", "お水を飲むかい", "drink", true),
        Case("case-112", "お茶を飲もうか", "drink", true),
        Case("case-113", "足", "feet", true),
        Case("case-114", "あし", "feet", true),
        Case("case-115", "アシ", "feet", true),
        Case("case-116", "足だね", "feet", true),
        Case("case-117", "足がかわいいね", "feet", true),
        Case("case-118", "足を見て", "feet", true),
        Case("case-119", "あしを見て", "feet", true),
        Case("case-120", "このあし", "feet", true),
        Case("case-121", "かわいいあし", "feet", true),
        Case("case-122", "両足だね", "feet", true),
        Case("case-123", "手", "hands", true),
        Case("case-124", "て", "hands", true),
        Case("case-125", "指", "hands", true),
        Case("case-126", "ゆび", "hands", true),
        Case("case-127", "手だね", "hands", true),
        Case("case-128", "てがかわいいね", "hands", true),
        Case("case-129", "指を見て", "hands", true),
        Case("case-130", "このて", "hands", true),
        Case("case-131", "かわいいゆび", "hands", true),
        Case("case-132", "両手だね", "hands", true),
        Case("case-133", "声", "voice", true),
        Case("case-134", "こえ", "voice", true),
        Case("case-135", "声だね", "voice", true),
        Case("case-136", "こえがかわいいね", "voice", true),
        Case("case-137", "このこえ", "voice", true),
        Case("case-138", "本", "book", true),
        Case("case-139", "ほん", "book", true),
        Case("case-140", "本だよ", "book", true),
        Case("case-141", "ほんを見て", "book", true),
        Case("case-142", "このほん", "book", true),
        Case("case-143", "服", "clothes", true),
        Case("case-144", "ふく", "clothes", true),
        Case("case-145", "服だね", "clothes", true),
        Case("case-146", "ふくを見て", "clothes", true),
        Case("case-147", "このふく", "clothes", true),
        Case("case-148", "歌", "music", true),
        Case("case-149", "うた", "music", true),
        Case("case-150", "歌だね", "music", true),
        Case("case-151", "うたを聞こう", "music", true),
        Case("case-152", "このうた", "music", true),
        Case("case-153", "お腹", "tummy", true),
        Case("case-154", "おなか", "tummy", true),
        Case("case-155", "おなかだね", "tummy", true),
        Case("case-156", "おなかを見て", "tummy", true),
        Case("case-157", "足りないね", "generic", true),
        Case("case-158", "足すよ", "generic", true),
        Case("case-159", "足し算だね", "generic", true),
        Case("case-160", "満足だね", "generic", true),
        Case("case-161", "不足だね", "generic", true),
        Case("case-162", "足場だね", "generic", true),
        Case("case-163", "足音だね", "generic", true),
        Case("case-164", "あしたね", "generic", true),
        Case("case-165", "あしらうよ", "generic", true),
        Case("case-166", "あしあとだね", "generic", true),
        Case("case-167", "あしもとを見て", "generic", true),
        Case("case-168", "手伝うよ", "generic", true),
        Case("case-169", "手紙だよ", "generic", true),
        Case("case-170", "手続きだね", "generic", true),
        Case("case-171", "苦手だね", "generic", true),
        Case("case-172", "指示だよ", "generic", true),
        Case("case-173", "ゆびわだね", "generic", true),
        Case("case-174", "なんてかわいい", "generic", true),
        Case("case-175", "してね", "generic", false),
        Case("case-176", "声優だね", "generic", true),
        Case("case-177", "こえるよ", "generic", true),
        Case("case-178", "本当だよ", "generic", true),
        Case("case-179", "本日だね", "generic", true),
        Case("case-180", "にほんだよ", "generic", true),
        Case("case-181", "服用だね", "generic", true),
        Case("case-182", "ふくらむね", "generic", true),
        Case("case-183", "歌舞伎だね", "generic", true),
        Case("case-184", "うたがうよ", "generic", true),
        Case("case-185", "あー", "generic", false),
        Case("case-186", "うー", "generic", false),
        Case("case-187", "あ", "generic", false),
        Case("case-188", "う", "generic", false),
        Case("case-189", "えっと", "generic", false),
        Case("case-190", "お腹が減ったね", "food", true),
        Case("case-191", "今日はなんだか不思議だね", "generic", true),
        Case("case-192", "たのむよ", "generic", true),
        Case("case-193", "頼みます", "generic", true),
        Case("case-194", "このみます", "generic", true),
        Case("case-195", "好みたい", "generic", true),
        Case("case-196", "のみかいに行くよ", "generic", true),
        Case("case-197", "飲み会に行くよ", "generic", true),
        Case("case-198", "ミルク飲むかい", "milk", true),
        Case("case-199", "みるくをのむ？", "milk", true),
        Case("case-200", "おっぱい飲みたい？", "milk", true),
        Case("case-201", "お風呂入ろっか", "bath", true),
        Case("case-202", "ミルク飲もっか", "milk", true),
        Case("case-203", "寝よっか", "sleep", true),
        Case("case-204", "そろそろ起きよっか", "wake", true),
        Case("case-205", "おむつ替えよっか", "diaper", true),
        Case("case-206", "着替えよっか", "clothes", true),
        Case("case-207", "抱っこする？", "hug", true),
        Case("case-208", "おてて握ってるね", "hands", true),
        Case("case-209", "あんよバタバタだね", "feet", true),
        Case("case-210", "にこって笑ったね", "smile", true),
        Case("case-211", "泣いてるね", "cry", true),
        Case("case-212", "いっぱいおしゃべりしてるね", "voice", true),
        Case("case-213", "げっぷ出たね", "tummy", true),
        Case("case-214", "一緒に遊ぼっか", "play", true),
        Case("case-215", "お散歩行こっか", "outside", true),
        Case("case-216", "雨だね", "rain", true),
        Case("case-217", "今日は晴れてるね", "sun", true),
        Case("case-218", "ごはん食べよっか", "food", true),
        Case("case-219", "絵本読もっか", "book", true),
        Case("case-220", "歌おっか", "music", true),
        Case("case-221", "寝る", "sleep", true),
        Case("case-222", "もう寝るよ", "sleep", true),
        Case("case-223", "寝たね", "sleep", true),
        Case("case-224", "寝かしつけよう", "sleep", true),
        Case("case-225", "睡眠の時間だよ", "sleep", true),
        Case("case-226", "寝ようか", "sleep", true),
        Case("case-227", "ねようか", "sleep", true),
        Case("case-228", "ねよっか", "sleep", true),
        Case("case-229", "もう寝よ", "sleep", true),
        Case("case-230", "ねんねしよっか", "sleep", true),
        Case("case-231", "眠ろうか", "sleep", true),
        Case("case-232", "眠る時間だよ", "sleep", true),
        Case("case-233", "お袋入ろうね", "bath", true),
        Case("case-234", "年々使用か", "sleep", true),
        Case("case-235", "おむづ変えようか", "diaper", true),
        Case("case-236", "みのく飲みますか", "milk", true),
        Case("case-237", "みのく飲もうか", "milk", true),
        Case("case-238", "お風呂入ろうね", "bath", true),
        Case("case-239", "授乳の時間だね", "milk", true),
        Case("case-240", "こんにちは、そろそろ寝ましょうね", "sleep", true),
        Case("case-241", "眠くなってきたね", "sleep", true),
        Case("case-242", "おもちゃで遊ぼうね", "play", true),
        Case("case-243", "絵本見ようか", "book", true),
        Case("case-244", "そろそろ飲むかい", "drink", true),
    )
    val sequences = listOf(
        Sequence("milk-followup", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("おいしいね", "milk", true),
        )),
        Sequence("milk-drinking", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("飲むかい？", "milk", true),
        )),
        Sequence("drink-new", listOf(
            Step("飲むかい？", "drink", true),
        )),
        Sequence("milk-water", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("お水を飲むかい？", "drink", true),
        )),
        Sequence("milk-bath", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("お風呂入ろうね", "bath", true),
        )),
        Sequence("book-expiry", listOf(
            Step("えほうを読もうね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "book", true),
            Step("いい感じですね", "generic", true),
        )),
        Sequence("drink-expiry", listOf(
            Step("飲むかい", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "drink", true),
            Step("いい感じですね", "generic", true),
        )),
        Sequence("milk-expiry", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "milk", true),
            Step("いい感じですね", "generic", true),
        )),
        Sequence("topic-switch", listOf(
            Step("ミルク飲もうね", "milk", true),
            Step("こんにちは そろそろ寝ましょうね", "sleep", true),
            Step("気持ちいいですね", "sleep", true),
            Step("えほうを読もうね", "book", true),
        )),
        Sequence("water-followup-reset", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("お水を飲むかい", "drink", true),
            Step("ゆっくりでいいよ", "drink", true),
            Step(reset = true),
            Step("いい感じですね", "generic", true),
        )),
        Sequence("milk-action-10", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲もうか", "milk", true),
        )),
        Sequence("milk-action-11", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲むかい", "milk", true),
        )),
        Sequence("milk-action-12", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲む？", "milk", true),
        )),
        Sequence("milk-action-13", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲みたい？", "milk", true),
        )),
        Sequence("milk-action-14", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲んだね", "milk", true),
        )),
        Sequence("milk-action-15", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲んでみよう", "milk", true),
        )),
        Sequence("milk-action-16", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("飲みましょうね", "milk", true),
        )),
        Sequence("milk-action-17", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("そろそろ飲む会", "milk", true),
        )),
        Sequence("milk-action-18", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("そろそろ飲むかい？", "milk", true),
        )),
        Sequence("milk-action-19", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("のむ？", "milk", true),
        )),
        Sequence("milk-action-20", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("のみたい？", "milk", true),
        )),
        Sequence("milk-action-21", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("のもうか", "milk", true),
        )),
        Sequence("milk-action-22", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("そろそろのむかい", "milk", true),
        )),
        Sequence("milk-action-23", listOf(
            Step("ミルクの時間だよ", "milk", true),
            Step("もうのんだね", "milk", true),
        )),
    )
}
