package com.eltnegcellist.emma.ai

import org.junit.Assert.*
import org.junit.Test

/** Fixtures captured from the published Web rules, including the ASR utterance gate. */
class LiteWebTopicParityTest {
    @Test fun publishedWebFixturesAgree() {
        val cases = listOf(
            Triple("てがみだよ", "generic", true),
            Triple("ほんとだね", "generic", true),
            Triple("ほんとうだね", "generic", true),
            Triple("こんにちは そろそろ寝ましょうね", "sleep", true),
            Triple("そろそろねましょうね", "sleep", true),
            Triple("もう寝ちゃったね", "sleep", true),
            Triple("ねむくなってきましたね", "sleep", true),
            Triple("そろそろ寝ませんか", "sleep", true),
            Triple("お昼寝の時間ですよ", "sleep", true),
            Triple("こんにちは、おふろに入りましょう", "bath", true),
            Triple("からだを洗いましょうね", "bath", true),
            Triple("おふらに入ろうね", "bath", true),
            Triple("ミルクを飲みましょうね", "milk", true),
            Triple("みるこを飲もうね", "milk", true),
            Triple("みりく飲もうか", "milk", true),
            Triple("ぼにゅうにしようね", "milk", true),
            Triple("ほにゅうびんだよ", "milk", true),
            Triple("そろそろ起きましょうね", "wake", true),
            Triple("おきましょうね", "wake", true),
            Triple("目を覚ましたね", "wake", true),
            Triple("おむつを取り替えましょう", "diaper", true),
            Triple("おむちをかえようね", "diaper", true),
            Triple("おしっこが出ましたね", "diaper", true),
            Triple("きがえましょうね", "clothes", true),
            Triple("洋服を着ましょうね", "clothes", true),
            Triple("ぱじゃまに着替えよう", "clothes", true),
            Triple("だっこしましょうね", "hug", true),
            Triple("だつこしようか", "hug", true),
            Triple("ぎゅっと抱きしめよう", "hug", true),
            Triple("おててをにぎってるね", "hands", true),
            Triple("てをにぎりましょうね", "hands", true),
            Triple("ゆびをつかんだね", "hands", true),
            Triple("あんよがばたばたしてるね", "feet", true),
            Triple("あしを動かしてるね", "feet", true),
            Triple("足を蹴っているね", "feet", true),
            Triple("かわいいえがおですね", "smile", true),
            Triple("にこにこしていますね", "smile", true),
            Triple("わらってるね", "smile", true),
            Triple("ないちゃったね", "cry", true),
            Triple("ぐずぐずしてるね", "cry", true),
            Triple("泣いていますね", "cry", true),
            Triple("ないてるね", "cry", true),
            Triple("こえを出しているね", "voice", true),
            Triple("おしゃべりしていますね", "voice", true),
            Triple("なんごが出たね", "voice", true),
            Triple("げっぷが出ましたね", "tummy", true),
            Triple("げつぷが出たね", "tummy", true),
            Triple("おなかいっぱいですね", "tummy", true),
            Triple("いっしょに遊びましょうね", "play", true),
            Triple("あそびましょうね", "play", true),
            Triple("おもちょで遊ぼうね", "play", true),
            Triple("さんぽに行きましょうね", "outside", true),
            Triple("べびーかーでお出かけしよう", "outside", true),
            Triple("こうえんに行こうね", "outside", true),
            Triple("あめが降っていますね", "rain", true),
            Triple("あまおとが聞こえるね", "rain", true),
            Triple("はれてきましたね", "sun", true),
            Triple("たいようが出ているね", "sun", true),
            Triple("ぽかぽかしていますね", "sun", true),
            Triple("ごはんを食べましょうね", "food", true),
            Triple("たべましょうね", "food", true),
            Triple("りにゅうしょくだよ", "food", true),
            Triple("おなかがすいたね", "food", true),
            Triple("えほんを読みましょうね", "book", true),
            Triple("えほうを読もうね", "book", true),
            Triple("ほんをよみましょうね", "book", true),
            Triple("うたを歌いましょうね", "music", true),
            Triple("おんがき聞こうね", "music", true),
            Triple("踊りましょうね", "music", true),
            Triple("こんにちは、今日もよろしくね", "generic", true),
            Triple("今日は会社で会議だったよ", "generic", true),
            Triple("今日はゆっくりしようね", "generic", true),
            Triple("かわいいね", "generic", true),
            Triple("いい感じですね", "generic", true),
            Triple("そろそろ帰りましょうね", "generic", true),
            Triple("お手紙を書きましょう", "generic", true),
            Triple("手続きをしましょう", "generic", true),
            Triple("手伝いましょうね", "generic", true),
            Triple("足りないですね", "generic", true),
            Triple("明日の予定を決めましょう", "generic", true),
            Triple("風呂敷を包みましょう", "generic", true),
            Triple("ふろしきを包もうね", "generic", true),
            Triple("歌舞伎を見よう", "generic", true),
            Triple("かぶきを見よう", "generic", true),
            Triple("声優さんの話だよ", "generic", true),
            Triple("せいゆうさんの話だよ", "generic", true),
            Triple("寝返りしましたね", "generic", true),
            Triple("ねがえりしたね", "generic", true),
            Triple("本当にそうですね", "generic", true),
            Triple("飴を買いましょう", "generic", true),
            Triple("紙を重ねるよ", "generic", true),
            Triple("みるこさんに会ったよ", "generic", true),
            Triple("紙を重ねましょう", "generic", true),
            Triple("かさねておきましょう", "generic", true),
            Triple("真似ましょう", "generic", true),
            Triple("友達をたずねましょう", "generic", true),
            Triple("飲もうか", "drink", true),
            Triple("飲むかい", "drink", true),
            Triple("飲む？", "drink", true),
            Triple("飲みたい？", "drink", true),
            Triple("飲んだね", "drink", true),
            Triple("飲んでみよう", "drink", true),
            Triple("飲みましょうね", "drink", true),
            Triple("そろそろ飲む会", "drink", true),
            Triple("そろそろ飲むかい？", "drink", true),
            Triple("のむ？", "drink", true),
            Triple("のみたい？", "drink", true),
            Triple("のもうか", "drink", true),
            Triple("そろそろのむかい", "drink", true),
            Triple("もうのんだね", "drink", true),
            Triple("お水を飲むかい", "drink", true),
            Triple("お茶を飲もうか", "drink", true),
            Triple("足", "feet", true),
            Triple("あし", "feet", true),
            Triple("アシ", "feet", true),
            Triple("足だね", "feet", true),
            Triple("足がかわいいね", "feet", true),
            Triple("足を見て", "feet", true),
            Triple("あしを見て", "feet", true),
            Triple("このあし", "feet", true),
            Triple("かわいいあし", "feet", true),
            Triple("両足だね", "feet", true),
            Triple("手", "hands", true),
            Triple("て", "hands", true),
            Triple("指", "hands", true),
            Triple("ゆび", "hands", true),
            Triple("手だね", "hands", true),
            Triple("てがかわいいね", "hands", true),
            Triple("指を見て", "hands", true),
            Triple("このて", "hands", true),
            Triple("かわいいゆび", "hands", true),
            Triple("両手だね", "hands", true),
            Triple("声", "voice", true),
            Triple("こえ", "voice", true),
            Triple("声だね", "voice", true),
            Triple("こえがかわいいね", "voice", true),
            Triple("このこえ", "voice", true),
            Triple("本", "book", true),
            Triple("ほん", "book", true),
            Triple("本だよ", "book", true),
            Triple("ほんを見て", "book", true),
            Triple("このほん", "book", true),
            Triple("服", "clothes", true),
            Triple("ふく", "clothes", true),
            Triple("服だね", "clothes", true),
            Triple("ふくを見て", "clothes", true),
            Triple("このふく", "clothes", true),
            Triple("歌", "music", true),
            Triple("うた", "music", true),
            Triple("歌だね", "music", true),
            Triple("うたを聞こう", "music", true),
            Triple("このうた", "music", true),
            Triple("お腹", "tummy", true),
            Triple("おなか", "tummy", true),
            Triple("おなかだね", "tummy", true),
            Triple("おなかを見て", "tummy", true),
            Triple("足りないね", "generic", true),
            Triple("足すよ", "generic", true),
            Triple("足し算だね", "generic", true),
            Triple("満足だね", "generic", true),
            Triple("不足だね", "generic", true),
            Triple("足場だね", "generic", true),
            Triple("足音だね", "generic", true),
            Triple("あしたね", "generic", true),
            Triple("あしらうよ", "generic", true),
            Triple("あしあとだね", "generic", true),
            Triple("あしもとを見て", "generic", true),
            Triple("手伝うよ", "generic", true),
            Triple("手紙だよ", "generic", true),
            Triple("手続きだね", "generic", true),
            Triple("苦手だね", "generic", true),
            Triple("指示だよ", "generic", true),
            Triple("ゆびわだね", "generic", true),
            Triple("なんてかわいい", "generic", true),
            Triple("してね", "generic", false),
            Triple("声優だね", "generic", true),
            Triple("こえるよ", "generic", true),
            Triple("本当だよ", "generic", true),
            Triple("本日だね", "generic", true),
            Triple("にほんだよ", "generic", true),
            Triple("服用だね", "generic", true),
            Triple("ふくらむね", "generic", true),
            Triple("歌舞伎だね", "generic", true),
            Triple("うたがうよ", "generic", true),
            Triple("あー", "generic", false),
            Triple("うー", "generic", false),
            Triple("あ", "generic", false),
            Triple("う", "generic", false),
            Triple("えっと", "generic", false),
            Triple("おなかがすいたね", "food", true),
            Triple("お腹が減ったね", "food", true)
        )
        for ((text, expectedScene, meaningful) in cases) {
            assertEquals("Scene: $text", expectedScene, LiteResponseEngine().respond(text).scene)
            assertEquals("Gate: $text", meaningful, MeaningfulJapaneseUtterance.isMeaningful(text))
            if (expectedScene !in listOf("generic", "drink")) {
                val context = LiteResponseEngine()
                context.respond("ミルクの時間だよ")
                assertEquals("Switch: $text", expectedScene, context.respond(text).scene)
                assertEquals("Stateless: $text", expectedScene, LiteResponseEngine().detectConcreteTopic(text)?.scene)
            }
        }
    }
    @Test fun drinkingContextAndSixTurnExpiry() {
        for (text in listOf("飲むかい", "飲もうか", "のむ？", "飲みたい？")) {
            val engine = LiteResponseEngine()
            assertEquals("drink", engine.respond(text).scene)
            for (i in 0 until 6) assertEquals("drink", engine.respond("いい感じですね").scene)
            assertEquals("generic", engine.respond("いい感じですね").scene)
            engine.respond("ミルクの時間だよ")
            assertEquals("milk", engine.respond(text).scene)
            val water = engine.respond("お水を飲むかい")
            assertEquals("drink", water.scene)
            assertFalse(water.english.contains("milk", ignoreCase = true))
            assertEquals("drink", engine.respond("ゆっくりでいいよ").scene)
            engine.resetConversationContext()
            assertEquals("generic", engine.respond("いい感じですね").scene)
        }
    }
}
